### ISSUE TITLE
Archive 出现错误

### ISSUE THREAD

**Issue by zuojx1013** [jinht/DocViewer#1]
你好，我用这个sdk在调试下一切正常，但是当archive的时候，提示错误，请问这个是什么原因呢？

**Comment by zuojx1013** [comment]
在工程配置里，将enable bitcode设置为NO，可以了。但是不知道会不会有什么副作用。

**Comment by jinht** [comment]
您描述的问题不是sdk的问题，而是xcode的配置问题，详情见链接：http://www.cnblogs.com/yxfBlogs/p/4946132.html

**Comment by basiralam** [comment]
Thanks @jinht for your reply...
