### ISSUE TITLE
下载缓存的问题.

### ISSUE THREAD

**Issue by dong136279559** [jinht/DocViewer#11]
下载过一次的文件,第二次打开不会去本地查找是否存在,是否可以能够去本地查找.

**Comment by jinht** [comment]
@dong136279559 
![81c87040-51e5-432f-b65f-152aec7832d9](https://user-images.githubusercontent.com/13724367/34332563-04fc0e42-e96d-11e7-85fa-342b94e5fe5c.png)

**Comment by dong136279559** [comment]
我想要实现的是,第一次下载之后,第二次点击不用下载直接访问本地数据,就算能够拿到下载完成后的url,这个是否还需要自己创建文件保存附件url和本地完成下载后路径url的关联呢?

**Comment by jinht** [comment]
@dong136279559 仔细看看代码
