### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by youbooks** [jinht/DocViewer#12]
你好，你这个demo里面，JhtDocViewerSDK 这个sdk 有源代码吗？

**Comment by jinht** [comment]
使用的时候可以参看demo或者SDK内相应.h文件

**Comment by youbooks** [comment]
主要是想阅读下这JhtDocViewerSDK代码， 不知道作者是否能开源？

**Comment by jinht** [comment]
sorry，之后会做开源考虑
