### ISSUE TITLE
你好，我想操作DocView上面的webview 获取页数

### ISSUE THREAD

**Issue by SmallWeed** [jinht/DocViewer#16]
你好，我想操作DocView上面的webview 获取页数 但是发现这部分好像没开源

**Comment by jinht** [comment]
@SmallWeed 是的，不好意思，webView 暂时没有暴露

**Comment by SmallWeed** [comment]
@jinht 能提供个属性，或接口 获取ScrollView 滚动的位置么？

**Comment by jinht** [comment]
@SmallWeed 暂时不能
