### ISSUE TITLE
.a文件

### ISSUE THREAD

**Issue by TML007** [jinht/DocViewer#2]

**Comment by jinht** [comment]
@TML007 有问题可以随时交流，我还在持续优化中

**Comment by Asingers** [comment]
好可惜,最近在学习和理解沙盒...但是相关的被打包.a 了.希望能够真正开源吧

**Comment by jinht** [comment]
@Asingers 有问题可以随时留言交流，还在持续优化中

**Comment by housenkui** [comment]
@jinht  我的哥哥啊，我想模仿一下您的代码，housenkui@gmail.com  🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉🍉

**Comment by a1274786993** [comment]
还是希望能开源一下,谢谢了
