### ISSUE TITLE
打开大文件

### ISSUE THREAD

**Issue by k214k** [jinht/DocViewer#6]
你好，代码支持能打开20M或更大文件doc或xlsx吗？

**Comment by jinht** [comment]
应该是可以的，我没有那么大的文件，只试过12M左右的

**Comment by k214k** [comment]
12M的文件，请问你打开的是pdf文件还是word文件？

**Comment by jinht** [comment]
@k214k  你有什么问题？

**Comment by k214k** [comment]
我就想使用你的sdk打开20M或者更大的word文件？因为我使用webview或wkview打开直接崩溃或打不开。

**Comment by jinht** [comment]
@k214k  那你试试啊

**Comment by k214k** [comment]
可以打开20M左右的，你能否把sdk的源码，开源出来？
